//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S2.L3C.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S2.L3C.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omkrets:{0, 8}\n.
        /// </summary>
        internal static string Area2D {
            get {
                return ResourceManager.GetString("Area2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höjd            :{0, 9}\n.
        /// </summary>
        internal static string Height3D {
            get {
                return ResourceManager.GetString("Height3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Längd  :{0, 8}\n.
        /// </summary>
        internal static string Length2D {
            get {
                return ResourceManager.GetString("Length2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Längd           :{0, 9}\n.
        /// </summary>
        internal static string Length3D {
            get {
                return ResourceManager.GetString("Length3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantelarea      :{0, 9}\n.
        /// </summary>
        internal static string MantelArea3D {
            get {
                return ResourceManager.GetString("MantelArea3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area   :{0, 8}\n.
        /// </summary>
        internal static string Perimeter2D {
            get {
                return ResourceManager.GetString("Perimeter2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1, 15}{2, 6}{3, 10}{4, 8}.
        /// </summary>
        internal static string Shape2DLine {
            get {
                return ResourceManager.GetString("Shape2DLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1, 15}{2, 6}{3, 6}{4, 12}{5, 12}{6, 12}.
        /// </summary>
        internal static string Shape3DLine {
            get {
                return ResourceManager.GetString("Shape3DLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begränsningsarea :{0, 9}\n.
        /// </summary>
        internal static string TotalSurfaceArea3D {
            get {
                return ResourceManager.GetString("TotalSurfaceArea3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volym           :{0, 9}\n.
        /// </summary>
        internal static string Volume3D {
            get {
                return ResourceManager.GetString("Volume3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bredd  :{0, 8}\n.
        /// </summary>
        internal static string Width2D {
            get {
                return ResourceManager.GetString("Width2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bredd           :{0, 9}\n.
        /// </summary>
        internal static string Width3D {
            get {
                return ResourceManager.GetString("Width3D", resourceCulture);
            }
        }
    }
}
